from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome()
driver.get("https://parabank.parasoft.com/parabank/index.htm?ConnType=JDBC")
driver.maximize_window()
register = driver.find_element(By.LINK_TEXT,"Register").click()
first = driver.find_element(By.ID,"customer.firstName")
last = driver.find_element(By.ID,"customer.lastName")
street = driver.find_element(By.ID,"customer.address.street")
city = driver.find_element(By.ID,"customer.address.city")
state = driver.find_element(By.ID,"customer.address.state")
zipcode = driver.find_element(By.ID,"customer.address.zipCode")
phone = driver.find_element(By.ID,"customer.phoneNumber")
ssn = driver.find_element(By.ID,"customer.ssn")
username = driver.find_element(By.ID,"customer.username")
password = driver.find_element(By.ID,"customer.password")
confirm = driver.find_element(By.ID,"repeatedPassword")
first.send_keys("Akkshee")
last.send_keys("Test")
street.send_keys("Mallasamudram")
city.send_keys("Namakkal")
state.send_keys("Tamil Nadu")
zipcode.send_keys("637503")
phone.send_keys("1234567890")
ssn.send_keys("1")
username.send_keys("Akksheetha123")
password.send_keys("Password@1234")
confirm.send_keys("Password@1234")
driver.find_element(By.XPATH, "//input[@value='Register']").click()
time.sleep(2)
bill_pay = driver.find_element(By.XPATH,"//a[normalize-space()='Bill Pay']").click()
pay = driver.find_element(By.NAME,"payee.name")
address = driver.find_element(By.NAME,"payee.address.street")
city = driver.find_element(By.NAME,"payee.address.city")
state = driver.find_element(By.NAME,"payee.address.state")
zipcode = driver.find_element(By.NAME,"payee.address.zipCode")
phone = driver.find_element(By.NAME,"payee.phoneNumber")
account = driver.find_element(By.NAME,"payee.accountNumber")
verify = driver.find_element(By.NAME,"verifyAccount")
amount = driver.find_element(By.NAME,"amount")
pay.send_keys("Akkshee")
address.send_keys("Mallasamudram")
city.send_keys("Namakkal")
state.send_keys("Tamil Nadu")
zipcode.send_keys("637503")
phone.send_keys("1234567890")
account.send_keys("123")
verify.send_keys("123")
amount.send_keys(1)
send_payment = driver.find_element(By.XPATH,"//input[@value='Send Payment']").click()
time.sleep(3)
success = driver.find_element(By.CSS_SELECTOR,"#billpayResult h1").text
assert "Bill Payment" in success
time.sleep(3)
driver.find_element(By.XPATH,"//a[normalize-space()='Accounts Overview']").click()
time.sleep(3)
total = driver.find_element(By.XPATH,"//table[@id='accountTable']//tr[2]//td[2]//b")
print(total.text)
assert total.is_displayed()
print("Done")
driver.quit()