from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver = webdriver.Chrome()
driver.get("https://automationexercise.com/")
driver.maximize_window()
wait = WebDriverWait(driver,10)
home = driver.find_element(By.XPATH,"//a[normalize-space()='Home']")
if home.is_displayed():
    print("Home page is visible")
login = driver.find_element(By.XPATH,"//a[normalize-space()='Signup / Login']")
driver.execute_script("arguments[0].click();", login)
wait.until(EC.visibility_of_element_located((By.NAME, "name")))
name = driver.find_element(By.NAME,"name")
email = driver.find_element(By.XPATH,"//input[@data-qa='signup-email']")
email.send_keys("akkshee35@gmail.com")
name.send_keys("Akkshee")
signup_btn = driver.find_element(By.XPATH,"//button[normalize-space()='Signup']")
driver.execute_script("arguments[0].click();", signup_btn)
wait.until(EC.visibility_of_element_located((By.NAME,"password")))
password = driver.find_element(By.NAME,"password")
password.send_keys("Password@1234")
fname = driver.find_element(By.NAME,"first_name")
lname = driver.find_element(By.ID,"last_name")
address = driver.find_element(By.ID,"address1")
state = driver.find_element(By.ID,"state")
city = driver.find_element(By.ID,"city")
zipcode = driver.find_element(By.ID,"zipcode")
mobile = driver.find_element(By.ID,"mobile_number")
fname.send_keys("Akkshee")
lname.send_keys("M")
address.send_keys("Namakkal")
state.send_keys("Tamil Nadu")
city.send_keys("Namakkal")
zipcode.send_keys("123456")
mobile.send_keys("1234567890")
create_btn = driver.find_element(By.XPATH,"//button[normalize-space()='Create Account']")
driver.execute_script("arguments[0].click();", create_btn)
account = driver.find_element(By.CSS_SELECTOR,"#form > div > div > div > h2 > b")
if account.is_displayed():
    print("Account Created successfully")
continue_btn = driver.find_element(By.XPATH,"//a[@class='btn btn-primary']")
driver.execute_script("arguments[0].click();", continue_btn)
wait.until(EC.visibility_of_element_located((By.XPATH, "//a[contains(text(), 'Logged in as')]")))
logged = driver.find_element(By.XPATH,"//a[contains(text(), 'Logged in as')]")
if logged.is_displayed():
    print("Logged with user name is visible")
product_btn = wait.until(EC.presence_of_element_located((By.XPATH, "(//div[@class='productinfo text-center'])[1]//a[@data-product-id='1']")))
driver.execute_script("arguments[0].click();", product_btn)
wait.until(EC.visibility_of_element_located((By.XPATH, "//button[@class='btn btn-success close-modal btn-block']")))
continue_shopping = driver.find_element(By.XPATH,"//button[@class='btn btn-success close-modal btn-block']")
assert continue_shopping.is_displayed()
driver.execute_script("arguments[0].click();", continue_shopping)
cart_lnk = driver.find_element(By.XPATH,"//a[contains(text(), 'Cart')]")
driver.execute_script("arguments[0].click();", cart_lnk)
wait.until(EC.visibility_of_element_located((By.XPATH,"//a[@class='btn btn-default check_out']")))
proceed = driver.find_element(By.XPATH,"//a[@class='btn btn-default check_out']")
driver.execute_script("arguments[0].click();", proceed)
wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR,"#address_delivery > li:nth-child(4)")))
check = driver.find_element(By.CSS_SELECTOR,"#address_delivery > li:nth-child(4)").text
assert check == "Namakkal"
print("Address is verified")
delete = driver.find_element(By.XPATH,"//a[normalize-space()='Delete Account']")
driver.execute_script("arguments[0].click();", delete)
wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, "#form > div > div > div > h2 > b")))
deleted = driver.find_element(By.CSS_SELECTOR,"#form > div > div > div > h2 > b").text
assert deleted == "ACCOUNT DELETED!"
print("Account is deleted")
driver.quit()